# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOGM767UEr5CVxZCxYUojsOZu4s1E5UC
"""

!ls /content/ASL_HG

!nvidia-smi

!pip install -q tensorflow opencv-python matplotlib seaborn

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!unzip -q /content/ASL_HG/ASL_Processed_Images.zip -d /content/ASL_HG/train



from google.colab import drive
drive.mount('/content/drive', force_remount=True)

ls "/content/ASL_HG/ASL-HG American Sign Language Hand Gesture Image D"

!mv "/content/ASL_HG/ASL-HG American Sign Language Hand Gesture Image D/ASL_HG_36000" \
   /content/ASL_HG/

!ls /content/ASL_HG/

rm -rf "/content/ASL_HG/ASL-HG American Sign Language Hand Gesture Image D"

!unzip -q /content/ASL_HG/ASL_HG_36000/ASL_Processed_Images.zip \
      -d /content/ASL_HG/data

!ls /content/ASL_HG/data/asl_processed/test

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# ------------------
# CONFIG
# ------------------
IMG_SIZE = 224
BATCH = 64
EPOCHS = 20

TRAIN_DIR = "/content/ASL_HG/data/asl_processed/train"
TEST_DIR  = "/content/ASL_HG/data/asl_processed/test"

# ------------------
# DATA GENERATORS
# ------------------
train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

test_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    TRAIN_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH,
    class_mode="categorical"
)

test_data = test_gen.flow_from_directory(
    TEST_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH,
    class_mode="categorical",
    shuffle=False
)

NUM_CLASSES = train_data.num_classes
print("Classes:", train_data.class_indices)

# ------------------
# MODEL (MobileNetV2)
# ------------------
base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model.trainable = False  # phase 1

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation="relu")(x)
x = Dropout(0.5)(x)
output = Dense(NUM_CLASSES, activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# ------------------
# CALLBACKS
# ------------------
callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True),
    ReduceLROnPlateau(patience=3, factor=0.3)
]

# ------------------
# TRAIN
# ------------------
history = model.fit(
    train_data,
    validation_data=test_data,
    epochs=15,
    callbacks=callbacks
)

# ------------------
# SAVE MODEL
# ------------------
model.save("/content/asl_hg_mobilenet.keras")
model.export("/content/asl_hg_savedmodel")

print("✅ Training complete and model saved")

# ------------------
# SAVE MODEL
# ------------------
model.save("/content/asl_hg_mobilenet.keras")
model.export("/content/asl_hg_savedmodel")

print("✅ Training complete and model saved")

# download keras model
from google.colab import files
files.download("/content/asl_hg_mobilenet.keras")

# zip + download SavedModel
!zip -r asl_hg_savedmodel.zip /content/asl_hg_savedmodel
files.download("asl_hg_savedmodel.zip")

# ------------------
# SAVE MODEL
# ------------------
model.save("/content/asl_hg_mobilenet.keras")   # Keras format
model.save("/content/asl_hg_mobilenet.h5")      # H5 format
model.export("/content/asl_hg_savedmodel")      # TensorFlow SavedModel

print("✅ Training complete and model saved")

from google.colab import files
files.download("/content/asl_hg_mobilenet.h5")

